# -*- coding: utf-8 -*-
"""ProjectAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5bwZFwxFEjMlCdUPRqsig0oKXqW0ddd
"""

import numpy as np
import pandas as pd

#load csv file
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep=";")
df

df.shape

data = df.sample(frac=0.9, random_state=786)
data_unseen = df.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

!pip install pycaret

from pycaret.regression import *
exp_reg101 = setup(data = data, target = 'alcohol', session_id=123)

best = compare_models(exclude = ['ransac'])

ada = create_model('ada')

print(ada)

lightgbm = create_model('lightgbm')

dt = create_model('dt')

tuned_ada = tune_model(ada)

import numpy as np
lgbm_params = {'num_leaves': np.arange(10,200,10),
                        'max_depth': [int(x) for x in np.linspace(10, 110, num = 11)],
                        'learning_rate': np.arange(0.1,1,0.1)
                        }
tuned_lightgbm = tune_model(lightgbm, custom_grid = lgbm_params)

print(tuned_lightgbm)

tuned_dt = tune_model(dt)

plot_model(tuned_lightgbm)

plot_model(tuned_lightgbm, plot = 'error')

plot_model(tuned_lightgbm, plot='feature')

predict_model(tuned_ada);

predict_model(tuned_dt);

predict_model(tuned_lightgbm);

final_ada = finalize_model(tuned_ada)
print(final_ada)

final_dt = finalize_model(tuned_dt)
print(final_dt)

final_lightgbm = finalize_model(tuned_lightgbm)
print(final_lightgbm)

predict_model(final_ada)

predict_model(final_dt)

predict_model(final_lightgbm);

unseen_predictions1 = predict_model(final_ada, data=data_unseen)
unseen_predictions1.head()

from pycaret.utils import check_metric
from sklearn.metrics import accuracy_score
print(check_metric(unseen_predictions1.alcohol, unseen_predictions1.Label, 'R2'))

# print(accuracy_score(unseen_predictions1.quality,unseen_predictions1.Label.astype(int)))

unseen_predictions2 = predict_model(final_dt, data=data_unseen)
unseen_predictions2.head()

print(check_metric(unseen_predictions2.alcohol, unseen_predictions2.Label, 'R2'))

# print(accuracy_score(unseen_predictions2.quality,unseen_predictions2.Label.astype(int)))

unseen_predictions3 = predict_model(final_lightgbm, data=data_unseen)
unseen_predictions3.head()

print(check_metric(unseen_predictions3.alcohol, unseen_predictions3.Label, 'R2'))

# print(accuracy_score(unseen_predictions3.quality,unseen_predictions3.Label.astype(int)))

save_model(final_lightgbm,'Final LightGBM Model 25Nov2020')

saved_final_lightgbm = load_model('Final LightGBM Model 25Nov2020')

new_prediction = predict_model(saved_final_lightgbm, data=data_unseen)

new_prediction.head()

from pycaret.utils import check_metric
check_metric(new_prediction.alcohol, new_prediction.Label, 'R2')